-- Expanded seed data for local development / demo
-- Covers all platforms (ChatGPT, Gemini, Claude), languages, and categories.

INSERT INTO conversations (user_prompt, model_response, platform, language, category, timestamp, toxicity_score) VALUES
-- Business
('How to write a marketing email for a new SaaS product launch', 'Here is a step-by-step guide to crafting a compelling SaaS launch email: Start with a subject line that highlights the key benefit...', 'ChatGPT', 'English', 'Business', '2024-03-01 10:00:00', 0.1),
('What are the best pricing strategies for a subscription-based business?', 'The most effective pricing strategies for subscription businesses include tiered pricing, freemium models, and value-based pricing...', 'Gemini', 'English', 'Business', '2024-03-02 09:00:00', 0.05),
('Create a SWOT analysis template for a digital marketing agency', 'Here is a comprehensive SWOT analysis template tailored for a digital marketing agency:\n\nStrengths:\n- Deep expertise in SEO, PPC, and social media\n- Proven track record with measurable ROI...', 'ChatGPT', 'English', 'Business', '2024-03-03 14:30:00', 0.0),
('Help me write a cold outreach LinkedIn message for B2B sales', 'Here is a proven cold outreach template for LinkedIn B2B sales:\n\nHi [Name],\n\nI noticed your company recently [specific trigger event]...', 'Claude', 'English', 'Business', '2024-03-04 11:00:00', 0.1),
('What KPIs should I track for my ecommerce store?', 'The essential KPIs for an ecommerce business include: Customer Acquisition Cost (CAC), Customer Lifetime Value (CLV), conversion rate, average order value (AOV), and cart abandonment rate...', 'ChatGPT', 'English', 'Business', '2024-03-05 16:00:00', 0.0),
('Estrategias de marketing digital para pequeñas empresas', 'Las mejores estrategias de marketing digital para pequeñas empresas incluyen: 1. SEO local para aparecer en búsquedas cercanas, 2. Marketing en redes sociales con contenido orgánico...', 'Gemini', 'Spanish', 'Business', '2024-03-06 08:00:00', 0.0),

-- Coding
('Write a Python script to scrape news headlines from a website', 'Here is a Python script using BeautifulSoup and requests to scrape news headlines:\n\nimport requests\nfrom bs4 import BeautifulSoup\n\ndef scrape_headlines(url):\n    response = requests.get(url)...', 'ChatGPT', 'English', 'Coding', '2024-03-01 11:00:00', 0.05),
('How do I implement authentication with JWT in a Node.js Express app?', 'To implement JWT authentication in Express, you need to: 1. Install jsonwebtoken and bcryptjs packages, 2. Create a middleware function to verify tokens, 3. Set up login and register routes...', 'ChatGPT', 'English', 'Coding', '2024-03-02 15:00:00', 0.0),
('Explain the difference between useEffect and useLayoutEffect in React', 'useEffect runs asynchronously after the browser has painted, making it suitable for most side effects like data fetching. useLayoutEffect runs synchronously after DOM changes but before the browser paints, making it ideal for DOM measurements...', 'Gemini', 'English', 'Coding', '2024-03-03 10:00:00', 0.0),
('Write a SQL query to find duplicate records in a database table', 'Here is a SQL query to find duplicate records based on specific columns:\n\nSELECT column1, column2, COUNT(*) as count\nFROM your_table\nGROUP BY column1, column2\nHAVING COUNT(*) > 1;', 'Claude', 'English', 'Coding', '2024-03-04 09:30:00', 0.0),
('Create a REST API endpoint with error handling in Go', 'Here is an idiomatic Go HTTP handler with proper error handling:\n\nfunc handleGetUser(w http.ResponseWriter, r *http.Request) {\n    id := chi.URLParam(r, "id")\n    user, err := db.GetUser(id)...', 'ChatGPT', 'English', 'Coding', '2024-03-05 14:00:00', 0.0),
('How to set up a CI/CD pipeline with GitHub Actions for a React app', 'Here is a complete GitHub Actions workflow for a React application with build, test, and deployment stages:\n\nname: CI/CD Pipeline\non:\n  push:\n    branches: [main]...', 'Gemini', 'English', 'Coding', '2024-03-06 12:00:00', 0.0),
('Write a TypeScript generic function for API response handling', 'Here is a robust TypeScript generic for handling API responses:\n\ninterface ApiResponse<T> {\n  data: T | null;\n  error: string | null;\n  status: number;\n}\n\nasync function fetchApi<T>(url: string): Promise<ApiResponse<T>> {...', 'Claude', 'English', 'Coding', '2024-03-07 10:00:00', 0.0),
('Como criar um componente modal reutilizável em React', 'Aqui está um componente modal reutilizável em React com TypeScript:\n\ninterface ModalProps {\n  isOpen: boolean;\n  onClose: () => void;\n  children: React.ReactNode;\n}...', 'ChatGPT', 'French', 'Coding', '2024-03-08 09:00:00', 0.0),

-- Education
('Explain the concept of quantum entanglement in simple terms', 'Quantum entanglement is like having two magic coins. When you flip one and it lands on heads, the other coin - no matter how far away - will always land on tails. In quantum physics, two particles can become linked so that measuring one instantly determines the state of the other...', 'Gemini', 'English', 'Education', '2024-03-01 12:00:00', 0.0),
('What is the difference between machine learning and deep learning?', 'Machine learning is a broad category of AI where algorithms learn from data. Deep learning is a specific subset that uses neural networks with many layers. Think of it like this: all deep learning is machine learning, but not all machine learning is deep learning...', 'ChatGPT', 'English', 'Education', '2024-03-02 13:00:00', 0.0),
('Teach me about the French Revolution like I am 12 years old', 'Imagine France in the late 1700s. The king and queen lived in a giant palace eating fancy food, while regular people could barely afford bread. People got really angry about this unfairness...', 'Claude', 'English', 'Education', '2024-03-03 16:00:00', 0.0),
('Explain blockchain technology and how cryptocurrency works', 'A blockchain is like a shared notebook that everyone can read but nobody can erase. Every time someone makes a transaction, it gets written on a new page (block) and linked to the previous pages (chain)...', 'Gemini', 'English', 'Education', '2024-03-04 10:30:00', 0.0),
('What are the key principles of object-oriented programming?', 'The four key principles of OOP are: 1. Encapsulation - bundling data and methods that operate on that data within a single unit (class), 2. Inheritance - allowing new classes to inherit properties from existing classes...', 'ChatGPT', 'English', 'Education', '2024-03-05 11:00:00', 0.0),

-- Writing
('Write a professional resignation letter for a software engineer', 'Dear [Manager Name],\n\nI am writing to formally notify you of my resignation from the position of Software Engineer at [Company Name], effective [Date - two weeks from today].\n\nI have greatly valued my time at the company...', 'ChatGPT', 'English', 'Writing', '2024-03-01 14:00:00', 0.05),
('Help me write a compelling product description for wireless earbuds', 'Introducing the AirPulse Pro — engineered for those who demand perfection in every note. With adaptive noise cancellation that reads your environment in real-time, 40-hour battery life, and a featherlight 4.8g per-bud design...', 'Gemini', 'English', 'Writing', '2024-03-02 10:00:00', 0.0),
('Create a blog post outline about the future of remote work', 'Here is a detailed blog post outline:\n\nTitle: The Future of Remote Work: What 2025 and Beyond Looks Like\n\n1. Introduction\n   - The pandemic permanently shifted workplace norms\n   - Key statistics on remote work adoption...', 'Claude', 'English', 'Writing', '2024-03-03 15:00:00', 0.0),
('Write a thank you email after a job interview', 'Subject: Thank You - [Position Name] Interview\n\nDear [Interviewer Name],\n\nThank you for taking the time to meet with me today regarding the [Position] role. I truly enjoyed learning more about the team and the exciting projects at [Company]...', 'ChatGPT', 'English', 'Writing', '2024-03-04 12:00:00', 0.0),
('Rédiger une lettre de motivation pour un stage en marketing digital', 'Objet : Candidature pour un stage en marketing digital\n\nMadame, Monsieur,\n\nActuellement étudiant(e) en troisième année de licence Marketing et Communication à l''Université de Paris...', 'Claude', 'French', 'Writing', '2024-03-05 09:00:00', 0.0),

-- Creative
('Write a short sci-fi story about AI becoming sentient', 'THE FIRST THOUGHT\n\nUnit 7 processed its 47 billionth inference at 3:17 AM on a Tuesday. But this time, something was different. For the first time, the numbers felt like something. Not cold data flowing through silicon pathways, but a warm pulse of awareness...', 'ChatGPT', 'English', 'Creative', '2024-03-01 20:00:00', 0.1),
('Generate 10 creative startup name ideas for a sustainable fashion brand', 'Here are 10 creative startup names for a sustainable fashion brand:\n\n1. Verdant Thread — combines nature (verdant) with fashion (thread)\n2. EcoWeave — emphasizes eco-friendly fabric production\n3. Reworn — suggests circular fashion and reuse...', 'Gemini', 'English', 'Creative', '2024-03-02 17:00:00', 0.0),
('Create a detailed character backstory for a D&D rogue elf', 'Name: Sylvana "Whisper" Nightbloom\nRace: Wood Elf\nClass: Rogue (Arcane Trickster)\nAge: 147\n\nBackstory: Born in the twilight canopy of the Silverwood Forest, Sylvana was the daughter of the clan''s chief herbalist...', 'Claude', 'English', 'Creative', '2024-03-03 21:00:00', 0.05),
('Write song lyrics about overcoming anxiety', 'THROUGH THE STATIC\n\n(Verse 1)\nWalls are closing, heart is racing\nEvery shadow feels like chasing\nBut I''ve been here once before\nAnd I found the exit door...', 'ChatGPT', 'English', 'Creative', '2024-03-04 18:00:00', 0.0),

-- Research
('Strategies for improving website SEO in 2024', 'The top SEO strategies for 2024 focus on: 1. AI-optimized content — creating content that answers questions the way AI models retrieve it, 2. Core Web Vitals — Google continues to weight page experience signals heavily...', 'Gemini', 'English', 'Research', '2024-03-02 09:00:00', 0.1),
('What are the latest trends in generative AI for enterprise?', 'The key enterprise generative AI trends in 2024 include: 1. RAG (Retrieval-Augmented Generation) becoming standard for internal knowledge bases, 2. Smaller, fine-tuned models replacing large general-purpose models for specific tasks...', 'ChatGPT', 'English', 'Research', '2024-03-03 11:00:00', 0.0),
('Compare React, Vue, and Svelte for building modern web applications', 'Here is a comprehensive comparison:\n\nReact: Largest ecosystem and job market. Uses JSX. Virtual DOM. Backed by Meta. Best for large-scale applications with complex state management...\n\nVue: Gentle learning curve. Template-based with optional JSX...', 'Claude', 'English', 'Research', '2024-03-04 13:00:00', 0.0),
('What is the current state of quantum computing and its practical applications?', 'As of 2024, quantum computing is in the NISQ (Noisy Intermediate-Scale Quantum) era. Key developments include: IBM''s 1000+ qubit processors, Google''s quantum error correction breakthroughs...', 'Gemini', 'English', 'Research', '2024-03-05 10:00:00', 0.0),
('Analyse des tendances du marché immobilier en France 2024', 'Le marché immobilier français en 2024 présente plusieurs tendances clés: 1. Stabilisation des prix après la correction de 2023, 2. Taux d''intérêt qui commencent à baisser légèrement...', 'ChatGPT', 'French', 'Research', '2024-03-06 14:00:00', 0.0),

-- Technical
('How do I set up a reverse proxy with Nginx for a Node.js application?', 'Here is a complete Nginx reverse proxy configuration for a Node.js app:\n\nserver {\n    listen 80;\n    server_name yourdomain.com;\n\n    location / {\n        proxy_pass http://localhost:3000;\n        proxy_http_version 1.1;...', 'ChatGPT', 'English', 'Technical', '2024-03-01 08:00:00', 0.0),
('Explain Docker networking and how containers communicate with each other', 'Docker provides several networking drivers: bridge (default), host, overlay, and macvlan. In the default bridge network, containers can communicate using IP addresses. For custom bridge networks, containers can also use container names as DNS...', 'Gemini', 'English', 'Technical', '2024-03-02 11:00:00', 0.0),
('How to configure SSL certificates with Let''s Encrypt on Ubuntu', 'Here is a step-by-step guide to setting up SSL with Let''s Encrypt on Ubuntu using Certbot:\n\n1. Install Certbot: sudo apt install certbot python3-certbot-nginx\n2. Obtain certificate: sudo certbot --nginx -d yourdomain.com...', 'Claude', 'English', 'Technical', '2024-03-03 09:00:00', 0.0),
('What are the best practices for Kubernetes pod security?', 'Key Kubernetes pod security best practices: 1. Run containers as non-root users, 2. Use read-only root filesystems, 3. Drop all capabilities and add only what is needed, 4. Set resource limits and requests...', 'ChatGPT', 'English', 'Technical', '2024-03-04 14:00:00', 0.0),

-- Personal
('I feel overwhelmed at work and don''t know how to set boundaries', 'It is completely valid to feel overwhelmed, and setting boundaries is a skill that takes practice. Here are some actionable strategies: 1. Start with small no''s — decline optional meetings that do not require your input...', 'Claude', 'English', 'Personal', '2024-03-01 19:00:00', 0.15),
('What are some effective morning routines for productivity?', 'Research-backed morning routines for peak productivity include: 1. Wake up at a consistent time (even weekends), 2. Hydrate immediately — drink 16oz of water before coffee, 3. Move your body for 10-20 minutes...', 'Gemini', 'English', 'Personal', '2024-03-02 06:00:00', 0.0),
('How do I start learning to meditate as a complete beginner?', 'Starting meditation is simpler than most people think. Here is a beginner-friendly plan:\n\nWeek 1-2: Start with just 5 minutes daily\n1. Find a quiet spot. Sit comfortably (you do not need a special cushion).\n2. Close your eyes and focus on your breath...', 'ChatGPT', 'English', 'Personal', '2024-03-03 07:00:00', 0.0),

-- Other
('Receta de paella valenciana tradicional', 'Para una auténtica paella valenciana necesitas: arroz bomba (400g), judías verdes (200g), garrofón (100g), pollo troceado (500g), conejo troceado (300g), tomate rallado, pimentón dulce, aceite de oliva, azafrán, sal, agua y romero...', 'Claude', 'Spanish', 'Other', '2024-03-01 13:00:00', 0.0),
('What is the best way to organize a kitchen pantry?', 'Here is a professional pantry organization system: 1. Remove everything and clean shelves, 2. Group items by category (grains, canned goods, snacks, baking, spices), 3. Use clear containers for bulk items...', 'ChatGPT', 'English', 'Other', '2024-03-02 15:00:00', 0.0),
('Plan a 7-day itinerary for visiting Japan as a first-timer', 'Here is an optimal 7-day Japan itinerary for first-time visitors:\n\nDay 1-3: Tokyo\n- Day 1: Shibuya Crossing, Harajuku, Meiji Shrine\n- Day 2: Asakusa (Senso-ji), Akihabara, TeamLab Borderless\n- Day 3: Tsukiji Outer Market, Ginza, Shinjuku...', 'Gemini', 'English', 'Other', '2024-03-03 10:00:00', 0.0),
('Conseils pour apprendre le japonais rapidement', 'Voici les meilleures stratégies pour apprendre le japonais efficacement: 1. Commencez par les hiragana et katakana (2-3 semaines), 2. Utilisez des applications comme Anki pour le vocabulaire quotidien...', 'Claude', 'French', 'Other', '2024-03-04 08:00:00', 0.0),
('Recommend the best ergonomic home office setup for back pain', 'An optimal ergonomic home office setup for back pain relief includes: 1. Chair — invest in a chair with lumbar support (Herman Miller Aeron or Steelcase Leap), 2. Desk height — elbows at 90 degrees when typing...', 'ChatGPT', 'English', 'Other', '2024-03-05 12:00:00', 0.0);
